services:
  database:
    ports:
      - '5432:5432'
    build:
      context: ./docker/database
    environment:
      POSTGRES_PASSWORD: postgres
  index:
    image: elasticsearch:8.18.1
    mem_limit: 1GB
    ports:
      - '9200:9200'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  message-broker:
    image: rabbitmq:4
    ports:
      - '5672:5672'